Allow squid includes dir and dummy file
mrlesmithjr/ansible-squid pull request #12
Opened 2018-10-16 12:56 UTC by lttmtins

To allow breaking up the squid.conf in separate logical files.

2018-10-18 03:37 UTC, mrlesmithjr requested changes

2018-10-18 03:37 UTC, mrlesmithjr commented on tasks/main.yml
> +
Add `become: true`

2018-10-18 03:37 UTC, mrlesmithjr commented on tasks/main.yml
> +    dest: "{{ squid_root_dir }}/conf.d/dummy.conf"
Add `become: true`

2020-08-19 23:52 UTC, goetzk commented
Hi,
In parallel to this I submitted a PR with some overlap (#15 ) , allowing the uploading of multiple files. I haven't investigated but rebasing this on to the current master might be a simple enough job to get it merged in.

2023-06-16 02:19 UTC, closed without merging